################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c \
C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.c 

OBJS += \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.o \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.o 

C_DEPS += \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.d \
./stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_msp_template.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_crc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dac.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma2d.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_lptim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usb.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.o: C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F769xx -DUSE_STM32F769I_DISCO -c -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/LAB-01-Template/inc" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/lovep/Documents/School/19F/MPS/workspace/stm32lib/STM32F7xx_HAL_Driver/Inc" -Og -ffunction-sections -Wall -Wdouble-promotion -fstack-usage -MMD -MP -MF"stm32lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

