/*
 * gpio.c
 *
 *  Created on: Sep 3, 2019
 *      Author: lovep
 */
#include "gpio.h"

void GPIO_Init()
{
	RCC->AHB1ENR |= // Configure the GPIO per
			RCC_AHB1LPENR_GPIOJLPEN |
			RCC_AHB1LPENR_GPIOALPEN |
			RCC_AHB1LPENR_GPIODLPEN |
			RCC_AHB1LPENR_GPIOFLPEN |
			RCC_AHB1LPENR_GPIOCLPEN;
	GPIOJ->MODER |= GPIO_MODER_MODER13_0 | GPIO_MODER_MODER5_0;
	GPIOA->MODER |= GPIO_MODER_MODER12_0;
	GPIOD->MODER |= GPIO_MODER_MODER4_0;

	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR7_0 | GPIO_PUPDR_PUPDR6_0;
	GPIOJ->PUPDR |= GPIO_PUPDR_PUPDR1_0;
	GPIOF->PUPDR |= GPIO_PUPDR_PUPDR6_0;
}
